
```{r}
if(!require(devtools)) install.packages("devtools")
if(!require(pacman)) install.packages("pacman")
pacman::p_load(
  dplyr, ggplot2, ggrepel, Hmisc, jsonlite, 
  lubridate, magrittr, NLP, plotly, readr, 
  readxl, rio, reshape2, rvest, stats,
  stringr, xml2,
  tidyverse, shiny, shinydashboard, DT, shinyjs)
if(!require(fontawesome)) install_github("rstudio/fontawesome", force = TRUE)
```

```{r}
library(devtools); library(pacman); library(dplyr); library(tidyverse); 
library(ggplot2); library(ggrepel); library(Hmisc); library(jsonlite); library(plotly);
library(lubridate); library(magrittr); library(NLP);  library(readr); 
library(readxl); library(rio); library(reshape2); library(rvest); library(stats);
library(stringr);library(xml2);
library(shiny); library(shinydashboard); library(DT); library(shinycustomloader); library(shinyjs)
start_time <- Sys.time()
```

```{r}
get.data <- function(no.stock) {
  base_url <- "https://finance.yahoo.com/quote/"
  l_url <- list(
    paste0(base_url, no.stock),
    paste0(base_url, no.stock, "?p=", no.stock),
    paste0(base_url, no.stock, "/financials?p=", no.stock),
    paste0(base_url, no.stock, "/balance-sheet?p=", no.stock),
    paste0(base_url, no.stock, "/cash-flow?p=", no.stock)
  )
  
  # Function to read HTML content from a URL with error handling
  read_html_with_error_handling <- function(url) {
    tryCatch(
      {
        read_html(url)
      },
      error = function(e) {
        # Check if it's a 404 error
        if (grepl("HTTP error 404", conditionMessage(e), fixed = TRUE)) {
          message("HTTP error 404 occurred for URL: ", url)
          return(NULL)
        } else {
          # Handle other errors
          message("An error occurred for URL: ", url, "\n", conditionMessage(e))
          return(NULL)
        }
      }
    )
  }
  
  # Read HTML content for each URL with error handling
  html_content_list <- lapply(l_url, read_html_with_error_handling)
  
  # Remove NULL elements from the list
  html_content_list <- Filter(Negate(is.null), html_content_list)
  
  return(html_content_list)
}
```

```{r}
"https://finance.yahoo.com/quote/AAPL" %>% read_html()
```

```{r}
get.data("AAPL")
```

```{r}
f4Periods <- function(no.stock){
  c_4periods <- c(); c_4periods[1:2] <- c("Breakdown", "TTM")
  xpath = paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[1]/div/div[3]") # column 3
  c_4periods[3] <- get.data(no.stock)[[3]] %>% html_nodes(xpath=xpath) %>% html_text %>% str_replace_all(., "/", "-")
  c_4periods[3] <- as.String((mdy(c_4periods[3]))) # column 3
  c_4periods[4] <- as.String((ymd(c_4periods[3]) - years(1))) # column 4
  c_4periods[5] <- as.String((ymd(c_4periods[3]) - years(2))) # column 5
  return(c_4periods)
}

f4Periods2 <- c("Breakdown", "TTM", "Period1", "Period2", "Period3")
```

```{r}
f4Periods("AAPL")
```


```{r}
vISbreakdowns <- c("Total Revenue", "Cost of Revenue", "Gross Profit", 
                   "Operating Expense", "Operating Income", "Total Expenses", "Net Income from Continuing & Discontinued Operation",
                   "EBIT", "EBITDA")

vBSbreakdowns <- c("Total Assets", "Total Liabilities Net Minority Interest", "Total Equity Gross Minority Interest", 
                   "Total Capitalization", "Common Stock Equity", "Capital Lease Obligations",
                   "Net Tangible Assets", "Invested Capital", "Tangible Book Value",
                   "Total Debt","Net Debt",
                   "Share Issued", "Ordinary Shares Number","Treasury Shares Number")
```

Cross Analysis
```{r}
fNum_tfrr <- function(df) {
  # Remove commas and convert to numeric
  df_cleaned <- as.data.frame(lapply(df, function(x) {
    # Remove commas and convert to numeric, handling NAs
    numeric_values <- as.numeric(gsub(",", "", x))
    ifelse(is.na(numeric_values), NA, numeric_values)
  }), stringsAsFactors = FALSE)
  
  return(df_cleaned)
}
```


Others
```{r}
Loader1 <- function(x){ withLoader(x, type="html", loader="loader1") }

BoxColor <- function(num){ 
  if(is.na(num)){ return("black") }
  if(as.numeric(num) < 0){ 
    return("red") } 
  else{ return("black") }
}
```

Ui
```{r}
ui <- dashboardPage( 
  skin = "black",
  
  dashboardHeader(
    title = "The YNow App",
    titleWidth = 250), #"calc(100% - 250)"
  
  dashboardSidebar(
    width = 250, # must same with titleWidth
    collapsed = TRUE,
    
    column(width = 12,
           sidebarSearchForm(textId = "searchText", buttonId = "searchButton", label = "Search..."), hr()
    ),
    column(width = 12,
           sidebarMenu(
             menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
             menuItem("Calculator", tabName = "calculator", icon = icon("equalizer", lib = "glyphicon"), 
                      badgeLabel = "new", badgeColor = "green"),
             menuItem("About", tabName = "about",  icon = icon("info-sign", lib = "glyphicon"))
           ), hr()
    ), 
    column(width = 12,
           radioButtons("periods", h5("Period Options"), choices = ""), hr(),
           h5("Recent Search:"),
           textOutput("recentsearch"), hr()
    ), 
    column(width = 12,
           textOutput("today"))
  ),
  
  dashboardBody(
    tags$head(tags$style(HTML('.main-header .logo { font-weight: bold }'))),
    
    fluidRow(
      column(width = 12,
             titlePanel(h2("Let's find some frauds from financial reports!"))
      ),
      column(width = 8,
             titlePanel(h5("a lawrence kuo shiny app")),
             textInput("sc", "Stock Code", value = "AAPL"), # set stock default
             submitButton("Search", icon("search"))
      ),
      column(width = 4,
             textOutput("txt_corpname"),
             #Loader1(uiOutput("imagesUI"))
      )), br(),
    
    fluidRow(
      infoBoxOutput("ibx_marketcap"),
      infoBoxOutput("ibx_stockprice"),
      infoBoxOutput("ibox_EPS")
    ),
    
    tabItems(
      tabItem(tabName = "dashboard",
              tabBox(title = "Financial Reports", width = "auto",
                     tabPanel("Finance Summary",
                              p("this section import Finance Summaries from Yahoo Finance"),
                              Loader1(dataTableOutput("tbFinanceSummary")),
                              downloadButton('FS_download',"Download the data")),
                     
                     tabPanel("Income Statement",
                              p("this section import Income Statements from Yahoo Finance"),
                              fluidRow( 
                                column(width = 6, 
                                       selectizeInput("is_breakdown", h5("Breaksdown Options"),                                 
                                                      choices = vISbreakdowns, selected = "Total Revenue",
                                                      multiple = FALSE),
                                       Loader1(plotlyOutput("plt_revenue", height = 300))
                                )
                              ),
                              Loader1(dataTableOutput("tbIncomeStatement")),
                              downloadButton('IS_download',"Download the data")),
                     
                     tabPanel("Balance Sheet",
                              p("this section import Balance Sheets from Yahoo Finance"),
                              fluidRow( 
                                column(width = 6, 
                                       selectizeInput("bs_breakdown", h5("Breakdown Options"),                                 
                                                      choices = vBSbreakdowns, selected = c("Total Assets", "Total Debt"),
                                                      multiple = TRUE),
                                       Loader1(plotOutput("pieCapitalStructure2", height = 300))
                                ),
                                column(width = 6,
                                       Loader1(plotOutput("pieCapitalStructure", height = 300)))
                              ),
                              Loader1(dataTableOutput("tbBalanceSheet")),
                              downloadButton('BS_download',"Download the data")),
                     
                     tabPanel("Cash Flow",
                              p("this section import Cash Flow datas from Yahoo Finance"),
                              Loader1(plotOutput("plt_3cashflow")),
                              Loader1(dataTableOutput("tbCashFlow")),
                              downloadButton('CF_download',"Download the data"))
              ),
              
              tabBox(title = "Performance", width = "auto",
                     tabPanel("KPI by Sheet",
                              fluidRow(
                                column(width = 12,
                                       h4("Balance Sheet KPI"),
                                       valueBoxOutput('vbx_eqt.mutiplier')
                                ),
                                column(width = 12,
                                       h4("Income Statement KPI"),
                                       valueBoxOutput('vbx_rev.growth'),
                                       valueBoxOutput('vbx_G.profit.gth'),
                                       valueBoxOutput('vbx_NNOIIE.EBIT'),
                                       valueBoxOutput('vbx_G.profit.margin'),
                                       valueBoxOutput('vbx_N.profit.margin')
                                ),
                                column(width = 12,
                                       h4("Cash FLow Statement KPI"),
                                       valueBoxOutput('vbx_OPCF.growth'),
                                       valueBoxOutput('vbx_IVCF.growth'),
                                       valueBoxOutput('vbx_FNCF.growth')
                                )
                              )
                     ),
                     
                     tabPanel("Crossover KPI",
                              fluidRow(
                                column(width = 12,
                                       valueBoxOutput('vbx_ROA'),
                                       valueBoxOutput('vbx_ROE'),
                                       valueBoxOutput('vbx_ast.turnover')
                                ),
                                column(width = 12,
                                       valueBoxOutput('vbx_ocf.NI'))
                              )      
                     )
              )
      ),
      
      # Define the UI elements using the variables
      tabItem(tabName = "calculator",
              tabBox(title = "Calculator", width = "auto",
                     tabPanel("Warnings",
                              fluidRow(
                                column(width = 12,
                                       textOutput("nofreecashflow"),
                                       #valueBoxOutput("vbx_fcf") 
                                ),
                                column(width = 12,
                                       textOutput("nooperatingcashflow"),
                                       #valueBoxOutput('vbx_OPCF.growth')
                                ),
                                column(width = 12,
                                       textOutput("notdoingbusiness"),
                                       #valueBoxOutput('vbx_rev.growth'),
                                       #valueBoxOutput('vbx_OPCF.growth')
                                ),
                                column(width = 12,
                                       textOutput("notgettingcashback"),
                                       #valueBoxOutput('vbx_opcf.NI')
                                )
                              )
                     )
              )
      ),
      
      tabItem(tabName = "about",
              tags$head(
                tags$style(HTML("pre { overflow: auto; word-wrap: normal; }"))),
              
              fluidRow(
                column(width = 12, h2("About The YNow App")),
                column(width = 8,
                       p("Red flags that may indicate financial fraud:", br(),
                         "- Unusual or unexpected increases in revenue or profits", br(),
                         "- Large, round numbers in the financial reports", br(),
                         "- Inflated or overstated assets", br(),
                         "- Unusual or unnecessary expenses or transfers between accounts", br(),
                         "- Unusual or inconsistent ratios or trends in the financial statements", br(),
                         "- Lack of adequate documentation or supporting evidence for transactions", br(),
                         "- Conflicts of interest among management or employees"
                       )
                ),
                column(width = 4,
                       h5("This is a web-based framework for building interactive data dashboards in R. 
                       The script loads a set of R packages for data processing, visualization and presentation, 
                       and sets up some functions for retrieving financial data from Yahoo Finance, 
                       extracting the relevant period data from the financial reports, 
                       and presenting the information in the form of tables and plots. 
                       The user interface is defined in the ui object and includes various inputs such as a text input for entering a stock code, 
                       info boxes for presenting summary information, and tabbed panels for displaying the finance summary, income statement and balance sheet. 
                       The data retrieval and processing are performed in the get.data and f4Periods functions, 
                       and the presentation of the data is done using Shiny components such as dataTableOutput and downloadButton."
                       )
                )
              )
      )
    )
  )
)
```

Server
```{r}
server <- function(input, output, session) {
  no.stock <- reactive({ input$sc })
  tmp <- reactive({
    req(input$sc)
    isolate(get.data(input$sc))
  })
  
  vPeriods <- c("Breakdown", "TTM", "Period1", "Period2", "Period3")
  observeEvent(input$sc, {
    updateRadioButtons(session, "periods", choices = vPeriods[2:5], selected = "TTM", inline = FALSE)
  })
  
  corp_name <- reactive({
    req(tmp())
    tmp()[[1]] %>%
      html_nodes(xpath = "//*[@id='quote-header-info']/div[2]/div[1]/div[1]/h1") %>% 
      html_text()
  })
  output$txt_corpname <- renderText({ corp_name() })
  
  ### FINANCE SUMMARY
  dFinanceSummary <- reactive({
    # overall breakdown
    df_financesummary <- data.frame()
    for(div in c(1:2)){
      for(tr in c(1:8)){
        for(i in c(1:2)){
          xpath_financesummary = paste0("//*[@id=\"quote-summary\"]/div[", div, "]/table/tbody/tr[", tr, "]/", "td[", i, "]")
          if(div==1){
            df_financesummary[tr, div+i-1] <- tmp()[[2]] %>% html_nodes(xpath=xpath_financesummary) %>% html_text
          }
          if(div==2){
            df_financesummary[tr, div+i] <- tmp()[[2]] %>% html_nodes(xpath=xpath_financesummary) %>% html_text
          }
        }
      }
    }
    colnames(df_financesummary) <- c("Name", "Value", "Name", "Value")
    return(df_financesummary)
  })
  
  output$tbFinanceSummary <- renderDataTable({ dFinanceSummary() })
  
  output$FS_download <- downloadHandler(
    filename = function() {
      paste0(as.character(no.stock()), "_financesummary_", as.character(Sys.Date()), ".csv")
    }, 
    content = function(file) {
      write.csv(dFinanceSummary(), file, row.names = FALSE)
    }
  )
  
  output$ibx_marketcap <- renderInfoBox({
    infoBox("Market Cap.",
            h3(dFinanceSummary()[1, 4], style = "font-size:150%;"),
            icon = icon("money-bill-trend-up"),
            color = "navy")
  })
  
  output$ibx_stockprice <- renderInfoBox({
    infoBox("Stock Price",
            h3(dFinanceSummary()[1, 2], style = "font-size:150%;"),
            icon = icon("money-bill"),
            color = "orange")
  })
  
  output$ibox_EPS <- renderInfoBox({
    infoBox("EPS",
            h3(dFinanceSummary()[4, 4], style = "font-size:150%;"),
            icon = icon("percent"),
            color = "green")
  })
  
  ### INCOME STATEMENT
  dIncomeStatement <- reactive({
    fIS_Path2Txt <- function(xpath){
      result <- tmp()[[3]] %>% html_nodes(xpath = xpath) %>% html_text
      ifelse(length(result)==0, return(NA), return(result))
    }
    
    ISxpath = paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[2]/div[", c(1:50), "]/div[1]/div[1]")
    no.row <- as.data.frame(sapply(ISxpath, fIS_Path2Txt), stringsAsFactors = FALSE)[, 1] %>% na.omit() %>% length()
    
    # overall breakdown
    df_financials <- data.frame(matrix(ncol = 5, nrow = no.row))
    for(div in c(1:no.row)){
      for(no.col in c(1:5)){
        xpath_financials = paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[2]/div[", div, "]/div[1]/div[", no.col, "]")
        df_financials[div, no.col] <- tmp()[[3]] %>% html_nodes(xpath=xpath_financials) %>% html_text
      }
    }
    colnames(df_financials) <- vPeriods
    return(df_financials)
  })
  
  output$tbIncomeStatement <- renderDataTable({ dIncomeStatement() })
  
  output$IS_download <- downloadHandler(
    filename = function(){ paste0(tolower(as.character(no.stock())), "_incomestatement_", as.character(Sys.Date()), ".csv") }, 
    content = function(x){ write.csv(dIncomeStatement(), x) }
  )
  
  # data charts
  actIncomeStatement <- reactive({
    dIncomeStatement()[c(1, which(colnames(dIncomeStatement()) == input$periods))] %>%
      filter(Breakdown %in% input$is_breakdown)
  })
  
  output$plt_revenue <- renderPlotly({
    dIncomeStatement() %>% filter(Breakdown %in% input$is_breakdown) %>%
      pivot_longer(
        cols = -Breakdown,
        names_to = "period",
        values_to = "amount") %>%
      ggplot(aes(x=fct_rev(factor(period)), y=amount)) +
      geom_col() +
      labs(title=paste("Plot of", input$is_breakdown, "by Periods"),
           x="period", y="amount")
  })
  
  # revenue growth
  rev.gth <- reactive({
    df_tmp <- fNum_tfrr(dIncomeStatement())
    idx <- which(dIncomeStatement()$Breakdown == "Total Revenue")
    rev.gth <- ((df_tmp[idx, 3]-df_tmp[idx, 4])/df_tmp[idx, 4]) + ((df_tmp[idx, 4]-df_tmp[idx, 5])/df_tmp[idx, 5]) / 2  
    return(rev.gth)
  })
  
  output$vbx_rev.growth <- renderValueBox({
    valueBox(
      round(rev.gth()*100, 2), "3yr Revenue gth (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(rev.gth())
    )
  })
  
  #Net Non Operating Interest Income Expense / EBIT
  NNOIIE.EBIT <- reactive({
    df_tmp <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Net Non Operating Interest Income Expense")
    idx2 <- which(dIncomeStatement()$Breakdown == "EBIT")
    NNOIIE.EBIT <- df_tmp[idx1, "TTM"] / df_tmp[idx2, "TTM"]
    return(NNOIIE.EBIT)
  })
  
  output$vbx_NNOIIE.EBIT <- renderValueBox({
    valueBox(
      round(NNOIIE.EBIT()*100, 2), "NNOIIE/EBIT (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(NNOIIE.EBIT())
    )
  })
  
  #Net Profit Margin Ratio: Net Income from Continuing Operation Net Minority Interest / Total Revenue
  N.profit.margin <- reactive({
    df_tmp <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Net Income from Continuing Operation Net Minority Interest")
    idx2 <- which(dIncomeStatement()$Breakdown == "Total Revenue")
    N.profit.margin <- df_tmp[idx1, "TTM"] / df_tmp[idx2, "TTM"]
    return(N.profit.margin)
  })
  
  output$vbx_N.profit.margin <- renderValueBox({
    valueBox(
      round(N.profit.margin()*100, 2), "N.Profit Margin (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(N.profit.margin())
    )
  })
  
  #Gross Profit Margin Ratio: Gross Profit / Total Revenue
  G.profit.margin <- reactive({
    df_tmp <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Gross Profit")
    idx2 <- which(dIncomeStatement()$Breakdown == "Total Revenue")
    G.profit.margin <- df_tmp[idx1, "TTM"] / df_tmp[idx2, "TTM"]
    return(G.profit.margin)
  })
  
  output$vbx_G.profit.margin <- renderValueBox({
    valueBox(
      round(G.profit.margin()*100, 2), "G.Profit Margin (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(G.profit.margin())
    )
  })
  
  #gross profit growth
  G.profit.gth <- reactive({
    df_tmp <- fNum_tfrr(dIncomeStatement())
    idx <- which(dIncomeStatement()$Breakdown == "Gross Profit")
    G.profit.gth <- ((df_tmp[idx, 3]-df_tmp[idx, 4])/df_tmp[idx, 4]) + ((df_tmp[idx, 4]-df_tmp[idx, 5])/df_tmp[idx, 5]) / 2  
    return(G.profit.gth)
  })
  
  output$vbx_G.profit.gth <- renderValueBox({
    valueBox(
      round(G.profit.gth()*100, 2), "3yr G.Profit gth (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(G.profit.gth())
    )
  })
  
  ### BALANCE SHEET
  dBalanceSheet <- reactive({
    fBS_Path2Txt <- function(xpath){
      result <- tmp()[[4]] %>% html_nodes(xpath = xpath) %>% html_text
      ifelse(length(result)==0, return(NA), return(result))
    }
    
    BSxpath = paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[2]/div[", c(1:50), "]/div[1]/div[1]")
    BStitle <- as.data.frame(sapply(BSxpath, fBS_Path2Txt), stringsAsFactors = FALSE)[, 1] %>% na.omit()
    no.row <- BStitle %>% length()
    
    # overall breakdown
    df_balancesheet <- data.frame()
    for(div in c(1:no.row)){
      df_balancesheet[div, 1] <- BStitle[div] #第一列標題
      for(no.col in c(2:5)){
        xpath_balancesheet = paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[2]/div[", div, "]/div[1]/div[", no.col, "]/span")
        htxt <- length(tmp()[[4]] %>% html_nodes(xpath=xpath_balancesheet) %>% html_text) 
        if(htxt==0){ 
          df_balancesheet[div, no.col] <- NA #剔除資料NA值
        } else{ 
          df_balancesheet[div, no.col] <- tmp()[[4]] %>% html_nodes(xpath=xpath_balancesheet) %>% html_text
        }
      }
    }
    colnames(df_balancesheet) <- vPeriods
    return(df_balancesheet)
  })
  
  output$tbBalanceSheet <- renderDataTable({ dBalanceSheet() })
  
  output$BS_download <- downloadHandler(
    filename = function(){ paste0(tolower(as.character(no.stock())), "_balancesheet_", as.character(Sys.Date()), ".csv") }, 
    content = function(x){ write.csv(dBalanceSheet(), x) }
  )
  
  # data charts
  output$pieCapitalStructure <- renderPlot({ 
    dBalanceSheet()[1:3, ] %>%
      select(Breakdown, TTM) %>%
      ggplot(aes(x="", y=TTM, fill=Breakdown)) +
      geom_bar(stat="identity", width=1, color="white") +
      coord_polar("y", start=0) +
      geom_label(aes(label = Breakdown),
                 position = position_stack(vjust = 0.5),
                 show.legend = FALSE) +
      theme_void()
  })
  
  actBalanceSheet <- reactive({
    dBalanceSheet()[c(1, which(colnames(dBalanceSheet()) == input$periods))] %>%
      filter(Breakdown %in% input$bs_breakdown)
  })
  
  output$pieCapitalStructure2 <- renderPlot({
    actBalanceSheet() %>% 
      ggplot(aes(x="", y=.[, 2], fill=Breakdown)) +
      geom_bar(stat="identity", width=1, color="white") +
      coord_polar("y", start=0) +
      geom_label(aes(label = Breakdown),
                 position = position_stack(vjust = 0.5),
                 show.legend = FALSE) +
      theme_void()
  })
  
  #Total Assets / Total Equity Gross Minority Interest
  eqt.mutiplier <- reactive({
    df_tmp <- fNum_tfrr(dBalanceSheet())
    idx1 <- which(dBalanceSheet()$Breakdown == "Total Assets")
    idx2 <- which(dBalanceSheet()$Breakdown == "Total Equity Gross Minority Interest")
    eqt.mutiplier <- df_tmp[idx1, "TTM"] / df_tmp[idx2, "TTM"]
    return(eqt.mutiplier)
  })
  
  output$vbx_eqt.mutiplier <- renderValueBox({
    valueBox(
      round(eqt.mutiplier(), 2), "Equity Multiplier", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(eqt.mutiplier())
    )
  })
  
  #Debt Ratio: Total Debt / Total Assests
  dbt.ratio <- reactive({
    df_tmp <- fNum_tfrr(dBalanceSheet())
    idx1 <- which(dBalanceSheet()$Breakdown == "Total Debt")
    idx2 <- which(dBalanceSheet()$Breakdown == "Total Assets")
    dbt.ratio <- df_tmp[idx1, "TTM"] / df_tmp[idx2, "TTM"]
  })
  
  output$vbx_dbt.ratio <- renderValueBox({
    valueBox(
      round(dbt.ratio(), 2), "Debt rto.", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(dbt.ratio())
    )
  })
  
  ### CASH FLOW
  dCashFlow <- reactive({
    fCF_Path2Txt <- function(xpath) {
      result <- tmp()[[5]] %>% html_nodes(xpath = xpath) %>% html_text
      ifelse(length(result) == 0, return(NA), return(result))
    }
    
    CFxpath <- paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[2]/div[", c(1:50), "]/div[1]/div[1]/div[1]/span")
    CFtitle <- as.data.frame(sapply(CFxpath, fCF_Path2Txt), stringsAsFactors = FALSE)[, 1] %>% na.omit()
    no.row <- length(CFtitle)
    
    # Check if CFtitle is empty, and return an empty data frame if it is
    if (no.row == 0) {
      return(data.frame())
    }
    
    # Overall breakdown
    df_cashflow <- data.frame()
    
    for (div in c(1:no.row)) {
      df_cashflow[div, 1] <- CFtitle[div]  # 第一列標題
      for (no.col in c(2:5)) {
        xpath_cashflow <- paste0("//*[@id=\"Col1-1-Financials-Proxy\"]/section/div[3]/div[1]/div/div[2]/div[", div, "]/div[1]/div[", no.col, "]/span")
        htxt <- length(tmp()[[5]] %>% html_nodes(xpath = xpath_cashflow) %>% html_text)
        if (htxt == 0) {
          df_cashflow[div, no.col] <- NA  # Replace with NA for missing values
        } else {
          df_cashflow[div, no.col] <- tmp()[[5]] %>% html_nodes(xpath = xpath_cashflow) %>% html_text
        }
      }
    }
    
    colnames(df_cashflow) <- vPeriods
    return(df_cashflow)
  })
  
  output$tbCashFlow <- renderDataTable({ dCashFlow() })
  
  output$CF_download <- downloadHandler(
    filename = function(){ paste0(tolower(as.character(no.stock())), "_cashflow_", as.character(Sys.Date()), ".csv") }, 
    content = function(x){ write.csv(dCashFlow(), x) }
  )
  
  opcf.gth <- reactive({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Operating Cash Flow")
    opcf.gth <- ((df_tmp[idx, 3]-df_tmp[idx, 4])/df_tmp[idx, 4]) + ((df_tmp[idx, 4]-df_tmp[idx, 5])/df_tmp[idx, 5]) / 2
    return(opcf.gth)
  })
  
  output$vbx_OPCF.growth <- renderValueBox({
    valueBox(
      round(opcf.gth()*100, 2), "3yr Operating CF gth (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(opcf.gth())
    )
  })
  
  ivcf.gth <- reactive({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Investing Cash Flow")
    ivcf.gth <- ((df_tmp[idx, 3]-df_tmp[idx, 4])/df_tmp[idx, 4]) + ((df_tmp[idx, 4]-df_tmp[idx, 5])/df_tmp[idx, 5]) / 2
    return(ivcf.gth)
  })
  
  output$vbx_IVCF.growth <- renderValueBox({
    valueBox(
      round(ivcf.gth()*100, 2), "3yr Investing CF gth (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(ivcf.gth())
    )
  })
  
  fncf.gth <- reactive({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Financing Cash Flow")
    fncf.gth <- ((df_tmp[idx, 3]-df_tmp[idx, 4])/df_tmp[idx, 4]) + ((df_tmp[idx, 4]-df_tmp[idx, 5])/df_tmp[idx, 5]) / 2
    return(fncf.gth)
  })
  
  output$vbx_FNCF.growth <- renderValueBox({
    valueBox(
      round(fncf.gth()*100, 2), "3yr Financing CF gth (%)", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(fncf.gth())
    )
  })
  
  # data charts
  actCashFlow <- reactive({
    dCashFlow()[c(1, which(colnames(dCashFlow()) == input$periods))]
  })
  
  output$plt_3cashflow <- renderPlot({
    df_tmp <- dCashFlow()[1:3, 1:5]
    df_tmp <- df_tmp %>% pivot_longer(
      cols = -Breakdown,
      names_to = "periods",
      values_to = "amount"
    )
    ggplot(df_tmp, aes(x = as.factor(periods), y = amount, group = Breakdown)) +
      geom_line(aes(color = Breakdown)) +
      labs(title = "Three Cash Flow Comparison", x = "periods", y = "amount")
  })
  
  ### Cross Analysis
  #ROA: Net Income from Continuing Operation Net Minority Interest	+ Net Interest Income *(1 - Tax Rate for Calcs) / mean(Total Assets 1, Total Assets 2)
  ROA <- reactive({
    df_tmp1 <- fNum_tfrr(dBalanceSheet()); df_tmp2 <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Net Income from Continuing Operation Net Minority Interest")
    idx2 <- which(dIncomeStatement()$Breakdown == "Net Interest Income")
    idx3 <- which(dIncomeStatement()$Breakdown == "Tax Rate for Calcs")
    idx4 <- which(dBalanceSheet()$Breakdown == "Total Assets")
    roa <- (df_tmp2[idx1, "TTM"] + df_tmp2[idx2, "TTM"] * (1 - df_tmp2[idx3, "TTM"])) / df_tmp1[idx4, "TTM"]
    return(roa)
  })
  
  output$vbx_ROA <- renderValueBox({
    valueBox(
      round(ROA()*100, 2), "ROA", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(ROA())
    )
  })
  
  #ROE: Net Income from Continuing Operation Net Minority Interest / mean(Total Equity Gross Minority Interest 1, Total Equity Gross Minority Interest 2)
  ROE <- reactive({
    df_tmp1 <- fNum_tfrr(dBalanceSheet()); df_tmp2 <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Net Income from Continuing Operation Net Minority Interest")
    idx2 <- which(dBalanceSheet()$Breakdown == "Total Equity Gross Minority Interest")
    roe <- df_tmp2[idx1, "TTM"] / df_tmp1[idx2, "TTM"]
    return(roe)
  })
  
  output$vbx_ROE <- renderValueBox({
    valueBox(
      round(ROE()*100, 2), "ROE", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(ROE())
    )
  })
  
  #Asset Turnover Ratio: 全年營收 / 期末總資產 
  ast.turnover <- reactive({
    df_tmp1 <- fNum_tfrr(dBalanceSheet()); df_tmp2 <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Total Revenue")
    idx2 <- which(dBalanceSheet()$Breakdown == "Total Assets")
    ast.turnover <- df_tmp2[idx1, "TTM"] / df_tmp1[idx2, "TTM"]
    return(ast.turnover)
  })
  
  output$vbx_ast.turnover <- renderValueBox({
    valueBox(
      round(ast.turnover(), 2), "Asset Turnover", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(ast.turnover())
    )
  })
  
  #營業現金流/稅後淨利
  opcf.NI <- reactive({
    df_tmp1 <- fNum_tfrr(dCashFlow()); df_tmp2 <- fNum_tfrr(dIncomeStatement())
    idx1 <- which(dIncomeStatement()$Breakdown == "Net Income from Continuing Operation Net Minority Interest")
    idx2 <- which(dCashFlow()$Breakdown == "Operating Cash Flow")
    opcf.NI <- df_tmp2[idx1, "TTM"] / df_tmp1[idx2, "TTM"]
    return(opcf.NI)
  })
  
  output$vbx_opcf.NI <- renderValueBox({
    valueBox(
      round(opcf.NI(), 2), "Operating CF/N.Income", icon = icon("thumbs-down", lib = "glyphicon"),
      color = BoxColor(opcf.NI())
    )
  })
  
  ### Fraud Warnings
  output$nofreecashflow <- renderText({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Free Cash Flow")
    fcf <- df_tmp[idx, "TTM"]
    if(fcf <= 0){ print("Warning 01: no free cash flow") }
  })
  
  output$vbx_fcf <- renderValueBox({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Free Cash Flow")
    fcf <- df_tmp[idx, "TTM"]
  })
  
  output$nooperatingcashflow <- renderText({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Operating Cash Flow")
    ocf <- df_tmp[idx, "TTM"]
    if(ocf <= 0){ print("Warning 02: no operating cash flow") }
  })
  
  output$vbx_opcf <- renderValueBox({
    df_tmp <- fNum_tfrr(dCashFlow())
    idx <- which(dCashFlow()$Breakdown == "Operating Cash Flow")
    opcf <- df_tmp[idx, "TTM"]
  })
  
  output$notdoingbusiness <- renderText({
    if(rev.gth() >= opcf.gth()){ print("Warning 03: not doing business") }
  })
  
  output$notgettingcashback <- renderText({
    if(opcf.NI() < 0.80){ print("Warning 04: not getting cash back") }
  })
  
  
  ### Others
  values <- reactiveValues()
  values$recentsearch <- c()
  observeEvent(input$sc, {
    # Add the current search term to the search history
    values$recentsearch <- c(values$recentsearch, corp_name())
    # Output the updated search history
    output$recentsearch <- renderText({
      paste(values$recentsearch, collapse = ", ")
    })
  })
  
  output$today <- renderText({
    format(Sys.Date(), "%Y/%m/%d")
  })
}
```

```{r}
shinyApp(ui = ui, server = server)
```

test 
```{r}
library(rvest)

# Define the URL
url <- "https://mops.twse.com.tw/mops/web/t164sb03"

# Try fetching the HTML content and handle errors
tryCatch({
  # Read the HTML content
  html_content <- read_html(url)
  
  # Extract table data
  table_data <- html_content %>%
    html_nodes(xpath = '//*[@id="div01"]/center/table[2]/tbody') %>%
    html_text() 
  
  print(table_data)
  
  # Convert table data to data frame
  if (length(table_data) > 0) {
    df <- as.data.frame(table_data[[1]])  # Assuming the first table contains the desired data
    # Optionally, you may clean or process the data frame here
    print(df)
  } else {
    cat("No table data found.\n")
  }
}, error = function(e) {
  cat("Error:", conditionMessage(e), "\n")
})
```

```{r}
url <- ("https://stockanalysis.com/stocks/")

page <- read_html(url)

stocks <- page %>%
  html_nodes('table#symbol-table') %>%
  html_table() %>% .[[1]]

stocks
```

